version: '3.8'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE='fastapi_db'
      - MYSQL_ROOT_PASSWORD='admin'
    ports:
      - "3307:3306"  # Map port 3307 on the host to port 3306 in the container
  backend-server:
    container_name: "backend-server"
    build: .    
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
