"""remove auto generate id in BaseModel

Revision ID: b3d6cb7a9037
Revises: d9aa6b12a434
Create Date: 2023-09-27 22:14:30.848238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d6cb7a9037'
down_revision: Union[str, None] = 'd9aa6b12a434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
